services:
    # client:
    #     build:
    #         context: ./client
    #         dockerfile: Dockerfile
    #     container_name: armadillo_client
    #     volumes:
    #         - ./client:/app
    #         - node_modules:/app/node_modules
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #     ports:
    #         - 8080:8080

    server:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        container_name: osrs_todo_server
        working_dir: /app/App
        volumes:
            - ./server/src:/app
            - /app/App/bin
            - /app/App/obj
        command: dotnet watch run --no-launch-profile --no-build
        environment:
            - ConnectionStrings__DefaultConnection=Host=psql;Database=osrs-todo;Username=osrs-todo;Password=osrs-todo;
            - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
        ports:
            - 5000:8080
        depends_on:
            psql:
                condition: service_started

    psql:
        container_name: osrs-todo-psql
        image: postgres:latest
        environment:
            - POSTGRES_USER=osrs-todo
            - POSTGRES_PASSWORD=osrs-todo
            - POSTGRES_DB=osrs-todo
        ports:
            - 5432:5432
        volumes:
            - osrs_todo_db:/home/postgres/pgdata/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U osrs-todo"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    osrs_todo_db:
    node_modules: